/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat" />

// NOTE: This file is automatically generated by Next.js when you run the development server.
// Do not edit or delete this file.